# Generated by Django 4.0.3 on 2023-01-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_film_age_alter_film_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='age',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='film',
            name='country',
        ),
        migrations.AddField(
            model_name='film',
            name='tag',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
