# Generated by Django 4.0.3 on 2023-01-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_age_film_year_remove_film_country_film_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='like',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
